### Лабораторная работа №1(часть 1) - "Работа с пакетом NumPy в Python"

Дан массив, содержащий баллы слушателей курса по английскому языку за вступительный экзамен. Слушатели распределены по 15 группам по 10 человек.

In [2]:
import numpy as np
scores = np.array([[20, 40, 56, 80, 0, 5, 25, 27, 74, 1],
         [0, 98, 67, 100, 8, 56, 34, 82, 100, 7],
         [78, 54, 23, 79, 100, 0, 0, 42, 95, 83],
         [51, 50, 47, 23, 100, 94, 25, 48, 38, 77],
         [90, 87, 41, 89, 52, 0, 5, 17, 28, 99],
         [32, 18, 21, 18, 29, 31, 48, 62, 76, 22],
         [6, 0, 65, 78, 43, 22, 38, 88, 94, 100],
         [77, 28, 39, 41, 0, 81, 45, 54, 98, 12],
         [66, 0, 88, 0, 44, 0, 55, 100, 12, 11],
         [17, 70, 86, 96, 56, 23, 32, 49, 70, 80],
         [20, 24, 76, 50, 29, 40, 3, 2, 5, 11],
         [33, 63, 28, 40, 51, 100, 98, 87, 22, 30],
         [16, 54, 78, 12, 25, 35, 10, 19, 67, 0],
         [100, 88, 24, 33, 47, 56, 62, 34, 77, 53],
         [50, 89, 70, 72, 56, 29, 15, 20, 0, 0]])
def prt(a, d):
    print("№"+ str(a) + " - "+ str(d))

### Задание 1

Посчитать, сколько слушателей получили 0 за вступительный экзамен.

In [3]:
prt(1,np.sum(scores==0))

№1 - 13


### Задание 2

Посчитать, сколько слушателей получили балл выше 50.

In [4]:
prt(2,np.sum(scores>50))

№2 - 64


### Задание 3

Посчитать, сколько человек получили балл не ниже 50, но не выше 70.

In [14]:
prt(3,np.sum((scores>=50) & (scores<=70)))

№3 - 26


### Задание 4

Определить, в какой группе средний балл за вступительный экзамен выше.

In [15]:
prt(4,np.average(scores, axis=1).argmax()+1)

№4 - 10


### Задание 5

Сохранить баллы слушателей выше 0 в массив `nonzero`. 

In [ ]:
nonzero = scores[np.where(scores>0)]
prt(5,nonzero)


№5 - [ 20  40  56  80   5  25  27  74   1  98  67 100   8  56  34  82 100   7
  78  54  23  79 100  42  95  83  51  50  47  23 100  94  25  48  38  77
  90  87  41  89  52   5  17  28  99  32  18  21  18  29  31  48  62  76
  22   6  65  78  43  22  38  88  94 100  77  28  39  41  81  45  54  98
  12  66  88  44  55 100  12  11  17  70  86  96  56  23  32  49  70  80
  20  24  76  50  29  40   3   2   5  11  33  63  28  40  51 100  98  87
  22  30  16  54  78  12  25  35  10  19  67 100  88  24  33  47  56  62
  34  77  53  50  89  70  72  56  29  15  20]


### Задание 6

Используя массив `nonzero`, определить минимальный балл за вступительный балл среди всех групп.

In [ ]:
prt(6,nonzero.min())

№6 - 1


### Задание 7

Выбрать из массива `nonzero` только те значения, которые соответствуют продвинутому уровню знания языка – баллу за экзамен выше 80. Сохранить полученный результат в массив `advanced`. 

In [ ]:
advanced = scores[np.where(scores>80)]
prt(7,advanced)


№7 - [ 98 100  82 100 100  95  83 100  94  90  87  89  99  88  94 100  81  98
  88 100  86  96 100  98  87 100  88  89]


### Задание 8

Получить из исходного массива `scores` массив медианных оценок по группам.

In [ ]:
prt(8,np.median(scores, axis=1))

№8 - [26.  61.5 66.  49.  46.5 30.  54.  43.  28.  63.  22.  45.5 22.  54.5
 39.5]


### Задание 9

Перераспределить студентов из `scores` в 10 групп по 15 человек с помощью метода `reshape`. Посчитать среднюю оценку в группе на обновленных данных.

In [ ]:
prt(9,np.average(scores.reshape(10,15),axis=1))

№9 - [40.06666667 55.53333333 60.8        33.73333333 47.93333333 44.4
 51.86666667 40.86666667 40.53333333 45.53333333]


### Задание 10

Определить общее число элементов в массиве `advanced`.

In [ ]:
prt(10,advanced.size)

№10 - 28


### Задание 11

На основе исходного массива `scores` создать булев массив `sto`, где `True` соответствует баллам за экзамен, равным 100, а `False` – всем остальным баллам. 

In [ ]:
sto = np.where(scores==100,True,False)
prt(11,sto)

№11 - [[False False False False False False False False False False]
 [False False False  True False False False False  True False]
 [False False False False  True False False False False False]
 [False False False False  True False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False False False False  True]
 [False False False False False False False False False False]
 [False False False False False False False  True False False]
 [False False False False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False  True False False False False]
 [False False False False False False False False False False]
 [ True False False False False False False False False False]
 [False False False False False False False False False False]]


### Задание 12

На основе исходного массива `scores` вывести на экран оценки слушателей первых семи групп (включительно, должны быть 7 списков оценок).

In [16]:
prt(12,scores[:7])

№12 - [[ 20  40  56  80   0   5  25  27  74   1]
 [  0  98  67 100   8  56  34  82 100   7]
 [ 78  54  23  79 100   0   0  42  95  83]
 [ 51  50  47  23 100  94  25  48  38  77]
 [ 90  87  41  89  52   0   5  17  28  99]
 [ 32  18  21  18  29  31  48  62  76  22]
 [  6   0  65  78  43  22  38  88  94 100]]


In [ ]:
from scipy.stats import mannwhitneyu

In [ ]:
from random import rand